apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ${APP_NAME}-drbd
  labels:
      app: ${APP_NAME}-drbd
      ${NODE_LABEL}: ""
      ${LUSTRE_FSNAME}/server: "drbd"
spec:
  selector:
    matchLabels:
      name: ${APP_NAME}-drbd
  template:
    metadata:
      labels:
        name: ${APP_NAME}-drbd
        ${NODE_LABEL}: ""
        ${LUSTRE_FSNAME}/server: "drbd"
    spec:
      hostNetwork: true
      nodeSelector:
        ${NODE_LABEL}: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: ${APP_NAME}
        image: ffornari/kube-lustre:drbd-containerized
        securityContext:
          privileged: true
        env:
        - name: RESOURCE_NAME
          value: "${APP_NAME}"
        - name: DEVICE
          value: "${DRBD_DEVICE}"
        - name: PROTOCOL
          value: "${DRBD_PROTOCOL}"
        - name: SYNCER_RATE
          value: "${DRBD_SYNCER_RATE}"
        - name: DEBUG
          value: "${DRBD_DEBUG:-0}"
        - name: NODE1_NAME
          value: "${NODE1_NAME}"
        - name: NODE1_IP
          value: "${NODE1_IP}"
        - name: NODE1_DISK
          value: "${DRBD_NODE1_DISK}"
        - name: NODE1_PORT
          value: "${DRBD_PORT}"
        - name: NODE2_NAME
          value: "${NODE2_NAME}"
        - name: NODE2_IP
          value: "${NODE2_IP}"
        - name: NODE2_DISK
          value: "${DRBD_NODE2_DISK}"
        - name: NODE2_PORT
          value: "${DRBD_PORT}"
        - name: FORCE_CREATE
          value: "${DRBD_FORCE_CREATE:-0}"
        volumeMounts:
          - name: devdir
            mountPath: /dev
          - name: kubedir
            mountPath: /root/.kube
      terminationGracePeriodSeconds: 60
      volumes:
        - name: devdir
          hostPath:
            path: /dev
            type: Directory
        - name: kubedir
          hostPath:
            path: /root/.kube
            type: Directory
